# Generated by Django 2.2.5 on 2021-03-03 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20210303_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_tyep',
            new_name='room_type',
        ),
    ]
